OPENAI_API_KEY= "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"
XAI_API_KEY= 'xai-SullCOxkLZrXMY7hJw9yLojWuziE5ruMLM8fFzCEiczOFysWIdSISFfoJsZ7ozSy2U1ulRLYIXpauogp'
MURAL_API_TOKEN="3a6f5868bd212d1d88aa28b70fcdefb283552f100c9b700b2e6bf8c2f7ebb9ff4cd239ab49caf4a57f89b574a66e53af231fa059aebfc63a8aa2db399ac4b327"
MURAL_ID=your-mural-id = "db4b1be9-4864-469c-931d-fc0cecde5ba5"
